Update patch set 1
Patch Set 1:

vendor/qcom/opensource/power/power-6150.c:124:41: error: a parameter list without types is only allowed in a function definition
int set_interactive_override(int UNUSED(on)) {

Patch-set: 1
CC: Gerrit User 6360 <6360@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>